### ISSUE TITLE
Locking overlay on 2nd display resets position.

### ISSUE THREAD

**Issue by DamnMyEyes** [iXab3r/MicSwitch#1]
My setup is two displays.  Display 1 (secondary) is 3840x2160 and display 2 (main) is 1920x1080.  I'm trying to position the overlay on display 1 but hitting the lock button resets it's position to the center of display 1.  It works great for display 2.

**Comment by TMady** [comment]
Having this issue as well. I have 3 monitors and every time I try to position overlay on anything but the primary display, it resets to the middle of the screen on the display I moved it to. If I try to move the overlay again, it simply resets itself to the middle of the monitor I'm on.

**Comment by iXab3r** [comment]
Should be fixed in v1.0.132
