### ISSUE TITLE
Option to lock selected microphone

### ISSUE THREAD

**Issue by tired9494** [iXab3r/MicSwitch#100]
I would greatly appreciate an option to be able to lock the selected microphone device. (i.e. to prevent it from switching to `All Devices` or any other option without the user manually selecting it). Currently, MicSwitch defaults back to `All Devices` when it cannot find the last selected microphone.

I use virtual audio cables so whenever MicSwitch reverts to `All Devices` my whole system is muted. Quite annoying having to go back through and unmute/adjust their volumes whenever this happens.

**Comment by iXab3r** [comment]
Done the change, if you can - please help me to test it out, I'll publish new release to github as soon as will be sure that it's stable, probably on a weekend https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.248.exe

From now on MicSwitch will not reset selection to All devices even if device is disconnected - it will show warning icon and will wait for device

**Comment by tired9494** [comment]
Alright, I've updated to it now and I'll let you know if I run into any issues

**Comment by tired9494** [comment]
[MicSwitch_1.0.248.0_release_20230107103836O316iDF00ULY.zip](https://github.com/iXab3r/MicSwitch/files/10366002/MicSwitch_1.0.248.0_release_20230107103836O316iDF00ULY.zip)

I got a crash when I let MicSwitch start immediately at startup (before the selected microphone became available)

There's also an issue where changing any of my output volumes changes all of them to the same volume while MicSwitch is running https://streamable.com/d70xqn Didn't have this issue before updating.

**Comment by iXab3r** [comment]
Fixed - https://eyeauras.blob.core.windows.net/shared/MicSwitchSetup.1.0.249.exe

**Comment by iXab3r** [comment]
should be fixed in 252, please reopen if it occurs again
