### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by JustinBrow** [iXab3r/MicSwitch#11]
Hello! I found your app while looking for a push to talk solution for Windows and thought I'd share my comments and the issues I encountered.

This is kind of a personal thing but I'd like to see an option to only toggle mute rather than forcing audio volume to be what is set in the app.

RAM usage of 100 megabytes seems kind of high, in my opinion, for what the app is supposed to do.

App creates a very shrunk all white window.
![234](https://i.imgur.com/QO8G41z.png)![229](https://i.imgur.com/ek4oqrg.png)

Open folder is labeled "Open PoeEye folder"
![147](https://i.imgur.com/5MDTfbk.png)

I realize this isn't the most technically accurate description of the issue but when using the MouseMiddle as a hotkey the app can create a state where mouse input is "blocked" except to the desktop, although maybe I shouldn't be using MouseMiddle as my hotkey in the first place.

The "Show main window" option in the doesn't work.
![195](https://i.imgur.com/yfFt6cJ.png)

App version: 0.126.0.0
Windows version: Windows 10 version 2004 64-bit

**Comment by iXab3r** [comment]
Hi ! First of all, thanks for such a thorough report :) 


> This is kind of a personal thing but I'd like to see an option to only toggle mute rather than forcing audio volume to be what is set in the app.
Good point. Will add checkbox for that.

> The "Show main window" option in the doesn't work. 
Known bug, will be fixed today/tomorrow

> Open folder is labeled "Open PoeEye folder"
Thanks ! Fixed in the next version

> App creates a very shrunk all white window.
Should also be fixed in the next version, but I am not 100% sure that the fix will work as this blank window is not visible on all my PCs for some reason.

> RAM usage of 100 megabytes seems kind of high, in my opinion, for what the app is supposed to do.
I will look into it, but it's the problem with .NET WPF Core applications - usually they are kinda memory-greedy. Even after optimizations I highly doubt that it will go below 50-60 megabytes just because it has quite high "base cost"

**Comment by iXab3r** [comment]
Will close this issue when I'll get a solution for RAM and Audio Volume poitns

**Comment by iXab3r** [comment]
Added volume control option in 1.0.134
Most of the issues are also should be fixed in that version. RAM  usage issue still stands

**Comment by iXab3r** [comment]
Updated .NET framework 4.5 to .NET 5

This changed memory footprint of application - it consumes a bit more memory on startup, but gradually falls down to 25-30mb.  I think it's acceptable, so I will close this issue

Note that it may seem that 1.0.160+ consumes much more memory than before, but in fact it is not - newer version of .NET Framework allocates far MORE memory than it actually needs, this is done to improve load time. After that it gradually releases memory either after some time or when Windows says that it needs RAM for some operation

![](https://i.imgur.com/BYS4rFi.png)
