### ISSUE TITLE
Choose custom mute/unmute sounds

### ISSUE THREAD

**Issue by DrSkunk** [iXab3r/MicSwitch#12]
The possibility to choose your own .mp3 or .wav files to hear when muted or unmuted.
I would use the default teamspreak or mumble sound effects instead of the built-in sounds.

I would add it myself, but currently I don't see where the current sound list is loaded in.

**Comment by Aramil-S** [comment]
Just swap files in \app-0.126.0\Resources\Notifications folder ;)

**Comment by iXab3r** [comment]
Please not that you'll have to do this after each update because this folder is version-specific.
I already have update version of a sound library that allows to select/load custom notifications, but it's not merged yet. Will probably be done in the few nearest versions

**Comment by iXab3r** [comment]
In v1.0.135 you can load custom notification from file
