### ISSUE TITLE
Malicious engine detected at virus total

### ISSUE THREAD

**Issue by shadowwarrior29** [iXab3r/MicSwitch#13]
I don't know if this has been properly checked by the community but Virustotal.com says there are malicious engines in the program. 

![image](https://user-images.githubusercontent.com/12261224/100570345-95b5df00-32f6-11eb-8def-4b82dc71e888.png)

**Comment by iXab3r** [comment]
Hi, that's a known issue that was reported previously. I've tried to contact virustotal support to get more details on heuristics, but  they simply went silent. I don't know for sure what part of the code triggers this check. 
I suppose these 2 alerts are triggered by the fact that application is not signed (signing certificate costs 200$ btw) and it controls system microphones. Application source code is open, it's quite easy to compile and compare resulting binaries with those hosted on github to verify integrity

**Comment by shadowwarrior29** [comment]
Got it. Thanks for the response.
