### ISSUE TITLE
Mics muted on app start

### ISSUE THREAD

**Issue by NTullio8** [iXab3r/MicSwitch#15]
All my microphones are at 0% volume when the app runs from startup. Then I am unable to change the volume slider without restarting the app manually.

**Comment by iXab3r** [comment]
Please try out the new version 1.0.136

**Comment by NTullio8** [comment]
The volume control is a helpful feature, however, it would be nice if there was a way to have it enabled on startup. Also, there have been a few instances of the app locking up and not updating the UI when a switch is clicked or using the volume slider although the action still goes through. For example, clicking the mute toggle will not display a blue/activated toggle but the microphones were in fact muted. The only way I have found to fix this is to end the task with the task manager and restart the app as the taskbar tray icon is also unresponsive in that state. Appreciate the support and hope this helps!

**Comment by iXab3r** [comment]
> The volume control is a helpful feature, however, it would be nice if there was a way to have it enabled on startup.
It may appear in the app at some point, but currently I am trying to avoid changing any microphone parameters on app startup. 

> Also, there have been a few instances of the app locking up 
Should be fixed in 1.0.160+

**Comment by iXab3r** [comment]
Will close for now
