### ISSUE TITLE
SecureAge APEX - Malicious report "Win/malicious_confidence_60% (W)"

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [iXab3r/MicSwitch#2]
Hey there.

Just want to mention that virustotal is resulting in a malicious report. I dont want to say that your binary is malicious but I think the people are a bit paranoid when using a software with mic-control :D

**MicSwitchSetup.0.114.0.exe -  Win/malicious_confidence_60% (W)** 
https://www.virustotal.com/gui/file/b55da2d945cb73eb26e9790ddf683667cb156adaf16ee0fc2e117931840be011/detection

**MicSwitch-0.114.0-full.nupkg - Gen:NN.ZexaE.34090.su0@a0jfGVd**
https://www.virustotal.com/gui/file/11c7a0685c16aa5f563d27288e562c2c60d59e3b5ea1955b4c9bf50df0f3bec2/detection

**Comment by iXab3r** [comment]
Somehow missed this issue. Thanks for raising it, I will try to find out what is triggering this alert

**Comment by iXab3r** [comment]
For 0.121 the result is 1/69 detection with 
**CrowdStrike Falcon Win/malicious_confidence_60% (W)**

Don't know what is triggering this alert though. But as it's only 1/69, 60% chance and no details about what exactly is triggering this heuristic I doubt I will be able to fix this false-positive
https://www.virustotal.com/gui/file/6e29edc1af32bb8e31988fab9eafb272a67556eec5b008045049f153c345a10c/detection
