### ISSUE TITLE
Overlay enhancement

### ISSUE THREAD

**Issue by lemiges** [iXab3r/MicSwitch#20]
Hello, I started to use your app and it is wonderful. 
I suggest one enhancement. It would be cool if I can move the overlay closer to top of screen in order to have the icon over applications title bar. 
I plan to use red and green boxes 400x20 pixels for icons.
Thanks 
PJ

**Comment by iXab3r** [comment]
Done, overlay could be now positioned much closer to edges of a screen (20x20 min)
