### ISSUE TITLE
Version 1.0.163 not starting - invalid keybind?

### ISSUE THREAD

**Issue by Manderius** [iXab3r/MicSwitch#26]
Hello,
after updating to the latest version, I got a quick error message. Unfortunately, I wasn't able to read it, but
I noticed it contained my mute key - Scroll Lock. The app crashed and I cannot start it again, so I suspect the keybind is causing problems. If I try to start the old version from "C:\Users\***\AppData\Local\MicSwitch\app-1.0.140" , it starts, but doesn't preserve settings (if I set keybind and settings and restart the app, they disappear), so I effectively cannot use the application.

Another separate issue (might be fixed in the newest version, can't test, because of the above): Audio notification for mute doesn't play the first time I mute my microphone, but microphone is muted and tray icon changes.

**Comment by iXab3r** [comment]
Hi, looking into it

**Comment by iXab3r** [comment]
Should be fixed in 1.0.166, although you'll have to set hotkey one more time
https://github.com/iXab3r/MicSwitch/releases/download/1.0.166/MicSwitchSetup.1.0.166.exe
