### ISSUE TITLE
Option : Only show overlay when muted or not depending your needs

### ISSUE THREAD

**Issue by LoneWolfProductions** [iXab3r/MicSwitch#27]
so you know you muted your mic. i  always forget to unmuted but would like to hide the overlay when i'm not muted.

it would be nice to only see the overlay when muted. 
or the other way around for who prefers that.

**Comment by iXab3r** [comment]
Sounds convenient, willl definitely implement this mode

**Comment by LoneWolfProductions** [comment]
Nice.

Thank you.

**Comment by iXab3r** [comment]
Implemented in 1.0.168
This version contains other changes that have to be tested before full release, so it will be published to auto-updater later, 
you can download it here if you want to be early adopter :) Please report if you'll encounter any bugs

https://cdn.discordapp.com/attachments/816795426258812949/816795481463717888/MicSwitchSetup.1.0.168.exe
