### ISSUE TITLE
Bug when alternating between two hotkeys

### ISSUE THREAD

**Issue by rday74** [iXab3r/MicSwitch#29]
Firstly, this software is awesome.
The problem is when I use alternately the two hotkeys that I have stored to toggle mute.
You will see the bug by doing this procedure:

Start unmuted:
Hotkey 1 to mute: works
Hotkey 2 to unmute: does not work
Hotkey 1 to unmute: does not work
Hotkey 2 to unmute: works

This does not strike me as intuitive behavior

**Comment by iXab3r** [comment]
Thanks for the report ! Should be fixed in the next version

**Comment by iXab3r** [comment]
Fixed in 1.0.181

**Comment by rday74** [comment]
Thanks a lot. I love this SW. Use it in all my meetings.
