### ISSUE TITLE
Failed to substitute modifier

### ISSUE THREAD

**Issue by lessafabio** [iXab3r/MicSwitch#30]
Hello,

I've been using MicSwitch v1.0.179.0 and randomly I'm receiving this error message below that can only be solved by closing and opening again the application.
The bad side is that you may be thinking that your microphone is muted, as in a meeting, and it is suddenly unmuted without you noticing.

[Microsoft Windows 10 Home Single Language (x64) Build 19042.868 (20H2)]

<img width="365" alt="Screen Shot 03-19-21 at 10 28 AM" src="https://user-images.githubusercontent.com/20400209/111788119-78555280-889e-11eb-81a3-7d52dc67b387.PNG">

**Comment by iXab3r** [comment]
Thanks for report ! Will be fixed in the next version

**Comment by iXab3r** [comment]
Fixed in 1.0.181
