### ISSUE TITLE
Keyboard shortcuts only trigger once

### ISSUE THREAD

**Issue by LeonHagenaarsKeus** [iXab3r/MicSwitch#31]
When using keyboard shortcuts, MicSwitch only once acts, only after closing the application and restarting, can I use the keyboard shortcut again.

Running Windows 10.
Current configuration:
![image](https://user-images.githubusercontent.com/7457283/112000606-6f72b400-8b1e-11eb-9f68-ddb4785491d8.png)

**Comment by iXab3r** [comment]
There we some improvements in hotkey handling done in 181-184, could you please check the latest version ?

**Comment by iXab3r** [comment]
Should be working correctly after all fixes in hotkey handling code
