### ISSUE TITLE
Micswitch v1.0.181.0 crashing (?) at start up

### ISSUE THREAD

**Issue by rday74** [iXab3r/MicSwitch#33]
Before the update (v1.0.179.0 I think) micswitch started up properly at startup in Win 10 version 1909.
Since the update to v1.0.181.0 , at start up I see a space appear in the taskbar where the microphone symbol normally appears. After a short time the space disappears. It turns out that micswitch is not running.
I then launch the application manually and then it works.

I wonder if something has changed between the two builds that has resulted in this change in behavior.

**Comment by rday74** [comment]
Update: It seems to be working ok now.

**Comment by iXab3r** [comment]
Closing due to self-fixing :)
