### ISSUE TITLE
FR: Dark Theme

### ISSUE THREAD

**Issue by lucaboox** [iXab3r/MicSwitch#4]
I have a dark windows theme and usually play games and stuff so the dark black mic button and white UI is a little annoying it would be nice to have a black/dark theme that inverts it and or makes the mic icon grey instead of black, I was thinking of just editing it for myself but I dunno if you think it's a good feature or not.

**Comment by iXab3r** [comment]
Probably option to select your own icon covers this case. This feature was implemented in v121 :)
[https://i.imgur.com/iYCwMxK.png](url)
