### ISSUE TITLE
Latest version (v1.0.188) flagged as malware by Chrome, Windows defender and Bitdefender

### ISSUE THREAD

**Issue by Alx05** [iXab3r/MicSwitch#42]
Hi,

I just tried to update to the latest version of the software and it seems that it's being detected as malware by ...well, everything. I had to revert to 1.0.186 to be able to use it. 

Thanks, the software is great, btw.

**Comment by iXab3r** [comment]
Hi, 
these are the changes from 186 to 188
Changed Min overlay size to 20x20 (cosmetical change)
Moved MicrophoneProvider to PoeShared (refactoring, nothing too fancy)
Added CancellationToken support to AudioPlayer (cancel ongoing sound notification if state changes)
MicSwitch overlay modifications - removed title, moved lock/opacity selector (UX change, nothing too fancy)

Have honestly no idea what could be triggering this alert in 188, but not trigger same alert in 186
