### ISSUE TITLE
Initial state: Mute should only Mute the microphone selected above

### ISSUE THREAD

**Issue by EduardMaschine** [iXab3r/MicSwitch#43]
Hi, just a thought.

I think the "initial state" option is quite handy, when you forget to mute your microphone when turning off your computer,
so that your microphone is on muted state when booting the PC up, rather then being active all the time. 

My issue now is, I use another 2,5mm jack to record audio from another resource. It's basically detected by Windows as a "microphone". Having the "Initial state" option set to "Mute" will mute all Microphones globally on Windows. Which would result in my "audio-in" being muted as well.

I would much rather have that application to mute the selected device under "Microphone" (Top option) instead of muting all microphones available on start.

I hope I described it clearly.
English is not my mother language and, to be honest, I just signed up here on GitHub just to mention it.

It's quite hard to get a software that is doing the work well and is still being maintained,
and your software does doing shit well except for that one little thing that bothers me. :) 

Best wishes and keep going with your awesome work!

![initialstatemutesallmics](https://user-images.githubusercontent.com/86126740/122604703-ac473c00-d076-11eb-8384-7c7e00e48e36.PNG)

**Comment by EduardMaschine** [comment]
Update: I just noticed that, when you set the "Initial state:" to "Do not change" it .. actually enables the Microphone again on Windows Boot... so it does change the state strangely from "off" before to "on". Tested it with via the app muted microphone a few times.

**Comment by iXab3r** [comment]
Should be fixed now, thanks for such a thorough report !
