### ISSUE TITLE
The hint is in the wrong place

### ISSUE THREAD

**Issue by im1x** [iXab3r/MicSwitch#44]
When you hover over the program icon in the tray, a hint with the program name and version number appears in the upper left corner.
![EgCsbiv7J0](https://user-images.githubusercontent.com/1444150/122753181-8a2e0380-d29a-11eb-96be-d45faab6c0a0.jpg)

**Comment by iXab3r** [comment]
should be fixed in 228+

**Comment by im1x** [comment]
> should be fixed in 228+
Just updated to version 1.0.234. The problem is still here.

**Comment by iXab3r** [comment]
That is one nasty little bug >.< Thx, will double-check the fix
on another system
