### ISSUE TITLE
5 modes needed.

### ISSUE THREAD

**Issue by davepk97080** [iXab3r/MicSwitch#5]
Whats really needed is a mutually exclusive selection of 5 different operating modes.

1) On (Talk)
2) Off (Mute)
3) Push to Talk
4) Push to Mute
5) Push On - Push Off (Toggle)

.

**Comment by iXab3r** [comment]
Will take a look, although some modes seem quite strange to me :) Push-to-mute specifically. Could you maybe elaborate on scenarios where this mode could be used ?

**Comment by iXab3r** [comment]
Added Push-to-mute in 1.0.135
So now we have 3 modes - Toggle, Push-to-talk and Push-to-mute
Enabling or disabling by different hotkeys is not implemented yet

**Comment by iXab3r** [comment]
Already implemented and will be released in the next version
https://discord.com/channels/513749321162686471/513749321750151169/824354379779932170

**Comment by iXab3r** [comment]
Implemented in 1.0.181
