### ISSUE TITLE
Installation creates a no-icon shortcut

### ISSUE THREAD

**Issue by Playnot** [iXab3r/MicSwitch#53]
After installation a shortcut with **no icon** is created:
![image](https://user-images.githubusercontent.com/60964225/127199144-fddfdb65-67a8-4fa6-ab82-a6e332be5323.png)
It seems the "Start in" field contains _"atures included within MicSwitch will allow seamless switching between chat apps while utilizing the "_
![image](https://user-images.githubusercontent.com/60964225/127199319-32f5ae9a-d177-4ea9-b193-66ebfcaf410a.png)

Edit: After clicking the "Change icon" button, the following error appears:
![image](https://user-images.githubusercontent.com/60964225/127199945-dc4b9b50-6aad-4d04-9c8d-0da829ca327c.png)

**Comment by iXab3r** [comment]
Thanks for reporting, will fix it on this weekend

**Comment by iXab3r** [comment]
fixed in 204
