### ISSUE TITLE
Unable to use in-app auto-updater

### ISSUE THREAD

**Issue by Playnot** [iXab3r/MicSwitch#54]
The automatic updater doesn't seem to work, this is the error message I'm seeing:
![image](https://user-images.githubusercontent.com/60964225/127386036-9f946073-6992-40a1-a77e-1a8663769e0a.png)

**Comment by iXab3r** [comment]
Hi! Thanks, the problem should be fixed in 193, please do the update manually by running the installer https://github.com/iXab3r/MicSwitch/releases/download/1.0.193/MicSwitchSetup.1.0.193.exe

**Comment by Playnot** [comment]
Can confirm that as of 1.0.195.0 it auto-updates successfully.

**Comment by iXab3r** [comment]
It sounds like restart component doesn't do it's job - it should've killed current instance and started a new one

**Comment by iXab3r** [comment]
Found the reason, will work on update and push it today/tomorrow

**Comment by iXab3r** [comment]
Made few improvements which should fix that behaviour in 196+

**Comment by Playnot** [comment]
It says it updated successfully, but it didn't autorestart.

**Comment by Playnot** [comment]
Updater works fine, installs new update, however there's no restart. It seems by design, not a bug.
Currently you have to click the new version icon to manually restart the app, so it switches to the new version.

**Comment by iXab3r** [comment]
There were some changes in how auto-updater works in the latest version (221). I'll close this issue as it's probably not relevant anymore
