### ISSUE TITLE
MicSwitch refuses to open after installing the updated version

### ISSUE THREAD

**Issue by samirotiv** [iXab3r/MicSwitch#69]
Running Windows 10, 64bit. Was working fine, then installed the latest version available as of now.

Micswitch doesn't open any more. Let me know if I can share any more info.

**Comment by leav6** [comment]
I have the same version (1.0.217) that no longer loads. It seems to put space for itself in the notification area but doesn't materialize. In Task Manager it appears but eventually disappears. Any debug logs to look at to help with this?

**Comment by AtmanActive** [comment]
Did you try deleting the conf folder at C:\Users\[XXX]\AppData\Roaming\MicSwitch ?

**Comment by leav6** [comment]
It actually turned out to be a change in Windows security policies. I was no longer able to run apps as administrator. Once I had that working again MicSwitch worked perfectly.

**Comment by iXab3r** [comment]
Thanks for helping out guys :)
