### ISSUE TITLE
How does the "push-to-talk" mode work with the keyboard?

### ISSUE THREAD

**Issue by godofr** [iXab3r/MicSwitch#7]
Hello.

Thanks for developing this app. It's what I've always been looking for ;-)

I am writing to let you know that I think the mode "push-to-talk" is not working well: I have set the F11 key as a hotkey. When I press the key the mute is activated, and when I release it the mute is deactivated. Shouldn't it be the opposite?

F11 press:
![F11-press](https://user-images.githubusercontent.com/24497812/92921528-782e5300-f434-11ea-8c72-c204ca6f3028.png)

F11 realease:
![F11-release](https://user-images.githubusercontent.com/24497812/92921546-7fedf780-f434-11ea-834a-098e31dbfc66.png)

Thank you very much!

**Comment by iXab3r** [comment]
Hi !  Hotkeys should be working as expected since early october, so I am closing this issue. Forgot to place a comment here earlier :)
