### ISSUE TITLE
BUG: Notification output device not saved

### ISSUE THREAD

**Issue by AtmanActive** [iXab3r/MicSwitch#75]
When MicSwitch is running, I can set a specific output device for the notification sounds and that's all working just fine.
But, when I quit MicSwitch and start it next time, the output device is again back to NULL.
When checking the .cfg file I can see that the name of the output device is there, but on next app start, it is removed.

This is what I see saved in the cfg:

`"OutputDeviceId": "{ Name = USB (USB Audio Device), ProductGuid = abcc5b84-c263-463b-a72f-a5bf64c86eba, ManufacturerGuid = 4e1cfa5e-1679-463b-a72f-a5bf64c86eba, NameGuid = fc575dd4-2f2e-463b-a72f-a5bf64c86eba }",`

Now, I don't know if that's important, but I never installed the app. 
I just unpacked it with UniversalExtractor and am running it like portable (even though I see that it is using _C:\Users\xxx\AppData\Roaming\MicSwitch_ for config).

**Comment by iXab3r** [comment]
Running it as portable should not be a problem - the only requirement is that it should have access to %appdata% to be able to write configs/logs/etc

In the latest version (221) there is "Report a problem"  button, could you please send me application logs ?

**Comment by iXab3r** [comment]
There were some fixes related to config handling and portability of the program, probably this issue is already obsolete
