### ISSUE TITLE
Crash maybe because my user account cannot elevate to administrator

### ISSUE THREAD

**Issue by leav6** [iXab3r/MicSwitch#81]
Hi Dmitry, 
Hopefully this will help in conjunction with my post in the Discussions tab.
[MicSwitch_1.0.223.0_pxWZkTSr_2022-02-07_111530.7z.zip](https://github.com/iXab3r/MicSwitch/files/8016859/MicSwitch_1.0.223.0_pxWZkTSr_2022-02-07_111530.7z.zip)

**Comment by iXab3r** [comment]
Fixed the crash in 226+ 
It was related to "Run at login" functionality - the lib I am using (StartupManager) for auto-start relies to Windows Tasks and they require administrator privileges. Probably the cleaner fix would be to remove this lib entirely and use some other approach (e.g. Startup folder or some other way), but I am using the same library for my other project and the update has to be done there first. This will be automatically pulled in for MicSwitch at some point in the future

Please report again if you'll still have problem after the update

**Comment by leav6** [comment]
Thanks @iXab3r,
I haven't observed a prompt to elevate to administrator, **thanks!**
Has the semi-transparent overlay lost the "always on top" attribute? 
I'll file a separate issue for it.
