### ISSUE TITLE
Did Microphone overlay lose the "always on top" attribute?

### ISSUE THREAD

**Issue by leav6** [iXab3r/MicSwitch#84]
**Steps to reproduce:**
1. Launched version 1.0.226 
2. Noticed the green microphone overlay
2. Used hotkey to toggle mute/unmute (may not be relevant to this issue)
3. Gave the focus to another application 
**Result**
The overlay is no longer visible. 
Minimizing other windows reveals the overlay is present. 
**expected**
The overlay should stay on top

**Comment by iXab3r** [comment]
There is no "Always on top" because overlays by default try to stay on top of other windows, maybe something broke in the last update, will check it today

**Comment by leav6** [comment]
Thanks for the explanation. 
I think the problem is actually a symptom of the other issue I just opened. I need to update the details on that. 
The overlay stopped appearing altogether,
and right-clicking the icon in the notification area did not produce context menu shown below:
----------------------
Show Main Window
----------------------
Exit app
----------------------

**Comment by leav6** [comment]
Thanks, yes, task manager worked. 
I updated the other issue.
Upon restarting it from Start menu, I did notice that 1.0.226 still prompted for elevated permissions. Is that expected?

**Comment by leav6** [comment]
I think this issue (overlay) can be closed.
