### ISSUE TITLE
MicSwitch icon overlay hiding behind applications

### ISSUE THREAD

**Issue by rizwans95** [iXab3r/MicSwitch#88]
Hello, the MicSwitch overlay icon used to always be on top of the window/application in use, and you would be able to click through it, which was awesome. However, now, the overlay icon actually gets hidden behind the window and is only visible when I minimize all applications and go to desktop. Can you bring that feature back?

**Comment by chuckz06** [comment]
yes i usually hidden when programs or games are in fullscreen mode, any way to fix this?

thanks in advance

**Comment by iXab3r** [comment]
will be fixed in scope of #96
