### ISSUE TITLE
Feature: Mute status on Discord

### ISSUE THREAD

**Issue by TheChilliPL** [iXab3r/MicSwitch#90]
Discord could get the global mute status if we registered this software as a certified audio device. If I understand it correctly, then people on Discord could see when your microphone is muted. Of course, it could be an optional feature.

Documentation: https://discord.com/developers/docs/topics/certified-devices

**Comment by iXab3r** [comment]
Problem is micswitch does not register itself as an input device anywhere in the system. Also having it's own device kinda contradicts with overall idea of controlling **other** system devices without any redirection/restream/whatsoever.
